import type { FeeGuideItem, OfficialSource } from "./types";

const VERIFIED_AT = "2026-09-03";

export const OFFICIAL_SOURCES: readonly OfficialSource[] = [
  {
    id: "fees-policy",
    title: "Etsy Fees & Payments Policy",
    url: "https://www.etsy.com/legal/fees/",
    sourceType: "policy",
    officialUpdatedAt: "2026-02-13",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: [
      "listing fee",
      "transaction fee rate and base",
      "Offsite Ads fee base and cap",
      "currency conversion fee",
    ],
    evidenceStatus: "confirmed",
    note: "The page's update date is not treated as the rule's effective date.",
  },
  {
    id: "etsy-payments-policy",
    title: "Etsy Payments Policy",
    url: "https://www.etsy.com/legal/etsy-payments/",
    sourceType: "policy",
    officialUpdatedAt: "2026-07-31",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["Etsy Payments scope", "payment account treatment"],
    evidenceStatus: "confirmed",
  },
  {
    id: "advertising-policy",
    title: "Etsy Advertising & Marketing Policy",
    url: "https://www.etsy.com/legal/advertising/",
    sourceType: "policy",
    officialUpdatedAt: "2026-06-08",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["Offsite Ads attribution", "Offsite Ads fee tiers", "Etsy Ads billing"],
    evidenceStatus: "confirmed",
  },
  {
    id: "fee-overview",
    title: "What are the Fees and Taxes for Selling on Etsy?",
    url: "https://help.etsy.com/hc/en-us/articles/115014483627-What-are-the-Fees-and-Taxes-for-Selling-on-Etsy",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["US seller fee overview", "private listing fee"],
    evidenceStatus: "confirmed",
  },
  {
    id: "payment-processing-rates",
    title: "What are Payment Processing Fees for Selling on Etsy?",
    url: "https://help.etsy.com/hc/en-us/articles/115015628847-What-are-Payment-Processing-Fees-for-Selling-on-Etsy",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["US rate of 3% plus $0.25 per order", "processing gross includes applicable tax"],
    evidenceStatus: "confirmed",
  },
  {
    id: "multiple-quantities",
    title: "Fees and Listing Multiple Quantities",
    url: "https://help.etsy.com/hc/en-us/articles/360000344908-Fees-and-Listing-Multiple-Quantities",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["multi-quantity listing debits", "sold-listing renewal behavior"],
    evidenceStatus: "partial",
    note: "The standard examples are confirmed; unusual renewal, credit, or listing states still require an actual debit count.",
  },
  {
    id: "offsite-ads-help",
    title: "How Etsy's Offsite Ads Work",
    url: "https://help.etsy.com/hc/en-us/articles/360000338367-How-Etsy-s-Offsite-Ads-Work",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["12% and 15% tiers", "$100 order cap", "30-day attribution", "participation threshold"],
    evidenceStatus: "confirmed",
  },
  {
    id: "share-save-help",
    title: "How to Save on Etsy Fees with the Share & Save Program",
    url: "https://help.etsy.com/hc/en-us/articles/16981332744087-How-to-Save-on-Etsy-Fees-with-the-Share-Save-Program",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["standard 4% fee refund", "30-day attribution"],
    evidenceStatus: "confirmed",
  },
  {
    id: "etsy-funded-coupons",
    title: "How Etsy Funded Coupons Work For Sellers",
    url: "https://help.etsy.com/hc/en-us/articles/1500005142242-How-Etsy-Funded-Coupons-Work-For-Sellers",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: [
      "seller receives the full order amount",
      "ordinary seller fees are unchanged",
      "Share & Save base excludes the promotional discount",
    ],
    evidenceStatus: "confirmed",
  },
  {
    id: "share-save-terms",
    title: "Etsy's Share & Save Program Terms",
    url: "https://www.etsy.com/legal/policy/etsys-share-save-terms-program-terms/1162874007996",
    sourceType: "program-terms",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["program eligibility", "eligible-order treatment", "attribution conditions"],
    evidenceStatus: "confirmed",
  },
  {
    id: "share-save-promotion",
    title: "Share & Save Intro Promotion Terms",
    url: "https://www.etsy.com/legal/policy/share-save-intro-promotion-terms/1498028396575",
    sourceType: "program-terms",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "variable",
    observedValidAt: VERIFIED_AT,
    supports: ["eligible introductory 6.5% refund", "seller-specific 14-day period"],
    evidenceStatus: "confirmed",
    note: "Eligibility and the seller-specific promotion window must be confirmed by the seller.",
  },
  {
    id: "texas-seller-fee-tax",
    title: "What are Sales and Use Taxes on Seller Fees in Texas?",
    url: "https://help.etsy.com/hc/en-us/articles/35267490737431-What-are-Sales-and-Use-Taxes-on-Seller-Fees-in-Texas",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "published",
    effectiveAt: "2025-10-01",
    supports: ["6.25% tax applied to 80% of the Etsy transaction fee", "Texas seller scope"],
    evidenceStatus: "confirmed",
    note: "MarginKit's use of the rounded transaction fee as the input is a disclosed product convention.",
  },
  {
    id: "us-sales-tax",
    title: "How US State Sales Tax and Fees Apply to Etsy Orders",
    url: "https://help.etsy.com/hc/en-us/articles/360000343968-How-US-State-Sales-Tax-and-Fees-Applies-to-Etsy-Orders",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["marketplace sales-tax collection", "Colorado Retail Delivery Fee"],
    evidenceStatus: "partial",
    note: "The source does not resolve whether Colorado's delivery fee enters the payment-processing base.",
  },
  {
    id: "shipping-labels",
    title: "How to Purchase Shipping Labels on Etsy",
    url: "https://help.etsy.com/hc/en-us/articles/360001967188-How-to-Purchase-Shipping-Labels-on-Etsy",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "variable",
    observedValidAt: VERIFIED_AT,
    supports: ["US shipping-label availability", "label cost depends on shipment details"],
    evidenceStatus: "confirmed",
  },
  {
    id: "shipping-insurance",
    title: "Insurance and Claims for Shipping Labels",
    url: "https://help.etsy.com/hc/en-us/articles/360001988847-Insurance-and-Claims-for-Shipping-Labels",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "variable",
    observedValidAt: VERIFIED_AT,
    supports: ["optional shipping-insurance cost"],
    evidenceStatus: "confirmed",
  },
  {
    id: "refunds",
    title: "How to Issue a Full or Partial Refund For an Order",
    url: "https://help.etsy.com/hc/en-us/articles/360002089188-How-to-Issue-a-Full-or-Partial-Refund-For-an-Order",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["refund fee credits", "cancellation and listing-fee treatment"],
    evidenceStatus: "confirmed",
  },
  {
    id: "payment-reserve",
    title: "What is a Payment Account Reserve?",
    url: "https://help.etsy.com/hc/en-us/articles/360058722214-What-is-a-Payment-Account-Reserve",
    sourceType: "help-center",
    verifiedAt: VERIFIED_AT,
    effectiveStatus: "not-published",
    observedValidAt: VERIFIED_AT,
    supports: ["reserve affects availability rather than order profit"],
    evidenceStatus: "confirmed",
  },
] as const;

export const FEE_GUIDE_ITEMS: readonly FeeGuideItem[] = [
  {
    id: "listing-unit",
    name: "Listing allocation",
    direction: "debit",
    calculation: "$0.20 x items sold",
    applicability: "Default long-run unit-economics allocation.",
    calculatorTreatment: "Automatic in Unit economics; actual order-triggered debit count is separate in Payment Account estimate.",
    sourceIds: ["fees-policy", "multiple-quantities"],
  },
  {
    id: "transaction",
    name: "Transaction fee",
    direction: "debit",
    calculation: "6.5% x seller gross order revenue (R)",
    applicability: "Supported US Etsy Marketplace orders.",
    calculatorTreatment: "Includes net item charges, personalization, buyer-paid shipping, and gift wrap; excludes US sales tax.",
    sourceIds: ["fees-policy"],
  },
  {
    id: "processing",
    name: "Etsy Payments processing fee",
    direction: "debit",
    calculation: "3% x processing gross (P) + $0.25 per order",
    applicability: "US bank account in the supported Etsy Payments scenario.",
    calculatorTreatment: "P defaults to seller revenue plus Etsy-collected sales tax; Statement mode permits an actual-base override.",
    sourceIds: ["payment-processing-rates", "etsy-payments-policy"],
  },
  {
    id: "offsite-ads",
    name: "Offsite Ads",
    direction: "debit",
    calculation: "12% or 15% x eligible revenue, capped at $100 per order",
    applicability: "Only for an attributed order; the seller confirms the applicable tier.",
    calculatorTreatment: "Selected through the mutually exclusive attribution control.",
    sourceIds: ["offsite-ads-help", "advertising-policy", "fees-policy"],
  },
  {
    id: "share-save",
    name: "Share & Save",
    direction: "credit",
    calculation: "Standard: 4% x max(0, R - E); confirmed intro with E = 0: 6.5% x R",
    applicability: "Only for an eligible attributed order.",
    calculatorTreatment: "The 6.5% intro cannot be combined with an Etsy-funded coupon in v1; no Share & Save option can be selected with Offsite Ads attribution.",
    sourceIds: ["share-save-help", "etsy-funded-coupons", "share-save-terms", "share-save-promotion"],
  },
  {
    id: "texas-tax",
    name: "Texas tax on seller fees",
    direction: "debit",
    calculation: "6.25% x 80% x transaction fee",
    applicability: "Texas shops, effective October 1, 2025, under the verified source.",
    calculatorTreatment: "Uses the already-rounded transaction fee, then rounds the tax line to cents as a MarginKit convention.",
    sourceIds: ["texas-seller-fee-tax"],
    caveat: "Etsy does not publish the complete intermediate penny-rounding sequence.",
  },
  {
    id: "sales-tax",
    name: "Marketplace sales tax",
    direction: "pass-through",
    calculation: "Actual tax from the Etsy receipt",
    applicability: "When Etsy collects applicable US marketplace sales tax.",
    calculatorTreatment: "Not seller revenue or operating cost; affects the payment-processing percentage base.",
    sourceIds: ["us-sales-tax", "payment-processing-rates"],
  },
  {
    id: "shipping-costs",
    name: "Shipping label and insurance",
    direction: "manual-cost",
    calculation: "Actual seller-entered amount",
    applicability: "When the seller incurs the cost.",
    calculatorTreatment: "Never inferred from order value; billing channel determines whether it enters the Statement estimate.",
    sourceIds: ["shipping-labels", "shipping-insurance"],
  },
] as const;

export const getOfficialSource = (id: string): OfficialSource | undefined =>
  OFFICIAL_SOURCES.find((source) => source.id === id);
